services:

  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - pipeline-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    networks:
      - pipeline-net

  app:
    build: ./app
    container_name: app
    ports:
      - "5000:5000"
    environment:
      VAULT_ADDR: http://vault:8200
    depends_on:
      - vault
      - postgres
    networks:
      - pipeline-net

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"                      # Jenkins UI at localhost:8080
      - "50000:50000"                    # agent communication port
    volumes:
      - jenkins_home:/var/jenkins_home   # persists Jenkins data between restarts
      - /var/run/docker.sock:/var/run/docker.sock  # lets Jenkins run docker commands
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - pipeline-net

volumes:
  jenkins_home:                          # named volume so Jenkins config survives restarts

networks:
  pipeline-net: